namespace FighteR_PG.Models
{
    public class Character
    {
        public int CharacterId { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Icon { get; set; }
        public string Specie { get; set; }
        public string Class { get; set; }
        public string Weapon { get; set; }
        public int Height { get; set; }
        public int Weight { get; set; }
        public int Age { get; set; }
        public string Likes { get; set; }
        public string Dislikes { get; set; }
        public string Hobby { get; set; }
        public string Food { get; set; }
        public string Curiosity { get; set; }
        public string Ideias { get; set; }
        public string Background { get; set; }
        public string Conclusao { get; set; }
        public string SkillName01 { get; set; }
        public string SkillName02 { get; set; }
        public string SkillName03 { get; set; }
        public string SkillName04 { get; set; }
        public string SkillName05 { get; set; }
        public string SkillName06 { get; set; }
        public string SkillName07 { get; set; }
        public string SkillName08 { get; set; }
        public string SkillName09 { get; set; }
        public string SkillName10 { get; set; }
        public string SkillName11 { get; set; }
        public string SkillName12 { get; set; }
        public string SkillDesc01 { get; set; }
        public string SkillDesc02 { get; set; }
        public string SkillDesc03 { get; set; }
        public string SkillDesc04 { get; set; }
        public string SkillDesc05 { get; set; }
        public string SkillDesc06 { get; set; }
        public string SkillDesc07 { get; set; }
        public string SkillDesc08 { get; set; }
        public string SkillDesc09 { get; set; }
        public string SkillDesc10 { get; set; }
        public string SkillDesc11 { get; set; }
        public string SkillDesc12 { get; set; }
        public string SkillImage01 { get; set; }
        public string SkillImage02 { get; set; }
        public string SkillImage03 { get; set; }
        public string SkillImage04 { get; set; }
        public string SkillImage05 { get; set; }
        public string SkillImage06 { get; set; }
        public string SkillImage07 { get; set; }
        public string SkillImage08 { get; set; }
        public string SkillImage09 { get; set; }
        public string SkillImage10 { get; set; }
        public string SkillImage11 { get; set; }
        public string SkillImage12 { get; set; }
        public string Special01 { get; set; }
        public string Special02 { get; set; }
        public string SpecialDesc01 { get; set; }
        public string SpecialDesc02 { get; set; }
        public string SpecialImage01 { get; set; }
        public string SpecialImage02 { get; set; }
        public string Fury { get; set; }
        public string Hit01 { get; set; }
        public string Hit02 { get; set; }
        public string StandComboImage01 { get; set; }
        public string StandComboImage02 { get; set; }
        public string WalkingComboImage01 { get; set; }
        public string WalkingComboImage02 { get; set; }
        public string RunningComboImage01 { get; set; }
        public string RunningComboImage02 { get; set; }
        public string JumpComboImage01 { get; set; }
        public string JumpComboImage02 { get; set; }
        public string RunningJumpComboImage01 { get; set; }
        public string RunningJumpComboImage02 { get; set; }
        public string StandCombo01 { get; set; }
        public string StandCombo02 { get; set; }
        public string WalkingCombo01 { get; set; }
        public string WalkingCombo02 { get; set; }
        public string RunningCombo01 { get; set; }
        public string RunningCombo02 { get; set; }
        public string JumpCombo01 { get; set; }
        public string JumpCombo02 { get; set; }
        public string RunningJumpCombo01 { get; set; }
        public string RunningJumpCombo02 { get; set; }
        public int ArchetypeId { get; set; }
        public virtual Archetype Archetype { get; set; }
        public int SexId { get; set; }
        public virtual Sex Sex { get; set; }
    }
}
